//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A1.A1Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="A1Reference.IA1Service")]
    public interface IA1Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1Service/IsInt", ReplyAction="http://tempuri.org/IA1Service/IsIntResponse")]
        bool IsInt(string userInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1Service/IsInt", ReplyAction="http://tempuri.org/IA1Service/IsIntResponse")]
        System.Threading.Tasks.Task<bool> IsIntAsync(string userInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1Service/PrimeNumber", ReplyAction="http://tempuri.org/IA1Service/PrimeNumberResponse")]
        string PrimeNumber(int userInput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IA1Service/PrimeNumber", ReplyAction="http://tempuri.org/IA1Service/PrimeNumberResponse")]
        System.Threading.Tasks.Task<string> PrimeNumberAsync(int userInput);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IA1ServiceChannel : A1.A1Reference.IA1Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class A1ServiceClient : System.ServiceModel.ClientBase<A1.A1Reference.IA1Service>, A1.A1Reference.IA1Service {
        
        public A1ServiceClient() {
        }
        
        public A1ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public A1ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A1ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public A1ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsInt(string userInput) {
            return base.Channel.IsInt(userInput);
        }
        
        public System.Threading.Tasks.Task<bool> IsIntAsync(string userInput) {
            return base.Channel.IsIntAsync(userInput);
        }
        
        public string PrimeNumber(int userInput) {
            return base.Channel.PrimeNumber(userInput);
        }
        
        public System.Threading.Tasks.Task<string> PrimeNumberAsync(int userInput) {
            return base.Channel.PrimeNumberAsync(userInput);
        }
    }
}
